name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - run: make format

      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.0

      - run: make test

      - run: make release
